### ISSUE TITLE
vulkan's performace problem and opengl on snapdragon 860

### ISSUE THREAD

**Issue by artud89** [Bankaimaster999/Dolphin-MMJR2#48]
I was playing twilight princess on mmjr 1 on snapdragon 860 in opengl in full hd however I was having problems with the gamepad, so I switched to mmjr2. however the performance in mmj2 went crazy, while in xiaomi's game boost in mmj1 in full hd it consumed at most 80% of the gpu in the heavier parts, in mmj2 it consumes 99% and much framedrop happens, which didn't happen before and if I put it in vulkan consumes a maximum of 55% of gpu but fps drop to 15-18 even with gpu having slack. I know the problem isn't my device.

**Comment by Bankaimaster999** [comment]
I guess no one reads anything these days ....
I made tons of disclaimers saying that MMJR2 "IS NOT A PERFORMANCE VARIANT" ... its a feature variant using the Dolphin Official source code. Its meant to act as a stepping stone so that we could port the performance changes after I fully investigate the performance changes of MMJR/MMJ for what makes it work as it does.

Therefore your "Issue" with MMJR2 ... is not an issue; you just didn't read any disclaimer about the project in the first place.

As for the gamepad issue for MMJR; this is not the right place to put that as this is for MMJR2. You would have better results posting that stuff in the discord server though since people will actively give you advice, but then again most controllers reported working just fine so you would have to eliminate the idea that its the controller compatibility that's an issue in this case.
